# Generated by Django 5.2.9 on 2025-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_site_payment_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepaymentsettings',
            options={},
        ),
        migrations.RenameField(
            model_name='sitepaymentsettings',
            old_name='card_holder',
            new_name='card_holder_name',
        ),
        migrations.RenameField(
            model_name='sitepaymentsettings',
            old_name='teacher_enroll_fee_z',
            new_name='teacher_enrollment_fee_z',
        ),
        migrations.AlterField(
            model_name='sitepaymentsettings',
            name='telegram_support',
            field=models.CharField(blank=True, help_text='e.g. @nok_support', max_length=120),
        ),
    ]
